$ErrorActionPreference = "Stop"

$dllPath = ".\skipframes-v1.11.1.dll"
$headerPath = ".\embedded_dll.h"

if (-not (Test-Path $dllPath)) {
    Write-Error "DLL not found at $dllPath. Compile it first."
    exit 1
}

Write-Host "Reading DLL bytes from $dllPath..."
$bytes = [System.IO.File]::ReadAllBytes($dllPath)
$hex = $bytes | ForEach-Object { "0x{0:X2}" -f $_ }
$hexString = $hex -join ","

Write-Host "Generating header content..."
$content = @"
// Auto-generated by embed_v2.ps1
#pragma once

const unsigned int g_DllSize = $($bytes.Length);
const unsigned char g_DllData[] = {
$hexString
};
"@

[System.IO.File]::WriteAllText($headerPath, $content)
Write-Host "Success: $headerPath created with size $($bytes.Length) bytes."
