
// skipframes.cpp
//
// compile: g++ -m32 -O2 -o skipframes.exe skipframes.cpp -static-libgcc
// -static-libstdc++ -s

#define _WIN32_WINNT 0x0501
#include "mingw_fix.h"
#include <TlHelp32.h>
#include <Windows.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <vector>

#include "embedded_dll.h" // Will be generated by compile.bat

// ============================================
// CONSOLE HELPERS
// ============================================

void Log(const char *fmt, ...) {
  char buf[1024];
  va_list args;
  va_start(args, fmt);
  vsprintf(buf, fmt, args);
  va_end(args);
  printf("%s", buf);
  OutputDebugStringA(buf);
}

// ============================================
// PROCESS HELPERS
// ============================================

DWORD GetProcessIdByName(const char *processName) {
  PROCESSENTRY32 pe32;
  pe32.dwSize = sizeof(PROCESSENTRY32);
  HANDLE hSnapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);

  if (hSnapshot == INVALID_HANDLE_VALUE)
    return 0;

  if (Process32First(hSnapshot, &pe32)) {
    do {
      if (lstrcmpiA(pe32.szExeFile, processName) == 0) {
        CloseHandle(hSnapshot);
        return pe32.th32ProcessID;
      }
    } while (Process32Next(hSnapshot, &pe32));
  }

  CloseHandle(hSnapshot);
  return 0;
}

// ============================================
// STANDARD INJECTION
// ============================================

bool DropFile(const char *path, const unsigned char *data, size_t size) {
  Log("[*] Dropping DLL to: %s\n", path);
  FILE *f = fopen(path, "wb");
  if (!f) {
    Log("[!] Failed to write file (Access Denied?)\n");
    return false;
  }
  fwrite(data, 1, size, f);
  fclose(f);
  return true;
}

bool InjectStandard(DWORD pid, const char *dllPath) {
  HANDLE hProc = OpenProcess(PROCESS_ALL_ACCESS, FALSE, pid);
  if (!hProc) {
    Log("[!] Failed to open process (Error: %d)\n", GetLastError());
    return false;
  }

  Log("[*] Process Opened. Allocating path memory...\n");
  void *pRemotePath = VirtualAllocEx(hProc, NULL, strlen(dllPath) + 1,
                                     MEM_COMMIT, PAGE_READWRITE);
  if (!pRemotePath) {
    Log("[!] VirtualAllocEx failed\n");
    CloseHandle(hProc);
    return false;
  }

  WriteProcessMemory(hProc, pRemotePath, dllPath, strlen(dllPath) + 1, NULL);

  Log("[*] Finding LoadLibraryA...\n");
  HMODULE hKernel32 = GetModuleHandleA("kernel32.dll");
  void *pLoadLibrary = (void *)GetProcAddress(hKernel32, "LoadLibraryA");

  Log("[*] Creating Remote Thread...\n");
  HANDLE hThread =
      CreateRemoteThread(hProc, NULL, 0, (LPTHREAD_START_ROUTINE)pLoadLibrary,
                         pRemotePath, 0, NULL);
  if (!hThread) {
    Log("[!] CreateRemoteThread failed (Error: %d)\n", GetLastError());
    VirtualFreeEx(hProc, pRemotePath, 0, MEM_RELEASE);
    CloseHandle(hProc);
    return false;
  }

  Log("[+] Injection Thread Started! Waiting for return...\n");
  WaitForSingleObject(hThread, INFINITE);

  DWORD exitCode = 0;
  GetExitCodeThread(hThread, &exitCode);
  Log("[+] Thread exited with code: 0x%X (HMODULE)\n", exitCode);

  CloseHandle(hThread);
  VirtualFreeEx(hProc, pRemotePath, 0, MEM_RELEASE);
  CloseHandle(hProc);

  if (exitCode == 0) {
    Log("[!] LoadLibrary failed in remote process (returned NULL)\n");
    return false;
  }

  return true;
}

// ============================================
// MAIN LOOP
// ============================================

int main() {
  Log("==========================================\n");
  Log("              SkipFrames\n");
  Log("==========================================\n");

  Log("[*] Waiting for hl.exe...\n");

  DWORD pid = 0;
  while (true) {
    pid = GetProcessIdByName("hl.exe");
    if (pid != 0)
      break;
    Sleep(1000);
  }

  Log("[+] Found hl.exe (PID: %d)\n", pid);

  char tempPath[MAX_PATH];
  GetTempPathA(MAX_PATH, tempPath);
  strcat(tempPath, "skipframes-v1.3.1.dll");

  // 1. Drop DLL
  if (!DropFile(tempPath, g_DllData, g_DllSize)) {
    Log("[!] Critical: Could not drop DLL.\n");
    system("pause");
    return 1;
  }

  // 2. Inject
  if (InjectStandard(pid, tempPath)) {
    Log("\n[SUCCESS] Injected!\n");
    Log("--- Commands ---\n");
    Log("  frame_skip <value>  - Skip frames (0=Off)\n");
    Log("  change_id <0/1>     - Toggle ID Changer\n");
    Log("  sb <0/1>            - Toggle SayiBilen (1=Ready)\n");
    Log("  sb_range <N>        - Guess Range (Default: 100)\n");
    Log("  sb_delay <MS>       - Delay in ms (Default: 5)\n");
    Log("  esp_ct <0/1>        - Toggle CT ESP\n");
    Log("  esp_t <0/1>         - Toggle T ESP\n");
    Log("  esp_type <1/2/3>    - 1=Glow 2=Box 3=Both\n");
    Log("  esp_label <0/1>     - Toggle Name+Distance Labels\n");
    Log("  F11                 - Toggle Stealth (Freeze-Patch-Thaw)\n");
    Log("--------------------\n");
  } else {
    Log("\n[!] Injection Failed.\n");
  }

  Log("\nYou can close this window now.\n");
  system("pause");
  return 0;
}
