
// skipframes.cpp
//
// compile: g++ -m32 -O2 -o skipframes.exe skipframes.cpp -static-libgcc
// -static-libstdc++ -s

#define _WIN32_WINNT 0x0501
#include "mingw_fix.h"
#include <TlHelp32.h>
#include <Windows.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <vector>

#include "embedded_dll.h" // Will be generated by compile.bat

// ============================================
// CONSOLE HELPERS
// ============================================

void Log(const char *fmt, ...) {
  char buf[1024];
  va_list args;
  va_start(args, fmt);
  vsprintf(buf, fmt, args);
  va_end(args);
  printf("%s", buf);
  OutputDebugStringA(buf);
}

// ============================================
// PROCESS HELPERS
// ============================================

DWORD GetProcessIdByName(const char *processName) {
  PROCESSENTRY32 pe32;
  pe32.dwSize = sizeof(PROCESSENTRY32);
  HANDLE hSnapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);

  if (hSnapshot == INVALID_HANDLE_VALUE)
    return 0;

  if (Process32First(hSnapshot, &pe32)) {
    do {
      if (lstrcmpiA(pe32.szExeFile, processName) == 0) {
        CloseHandle(hSnapshot);
        return pe32.th32ProcessID;
      }
    } while (Process32Next(hSnapshot, &pe32));
  }

  CloseHandle(hSnapshot);
  return 0;
}

// ============================================
// MANUAL MAPPING INJECTION
// ============================================

typedef HMODULE(__stdcall *pLoadLibraryA)(const char *);
typedef FARPROC(__stdcall *pGetProcAddress)(HMODULE, const char *);
typedef BOOL(__stdcall *pDllMain)(HINSTANCE, DWORD, LPVOID);

struct ManualMappingData {
  pLoadLibraryA fnLoadLibraryA;
  pGetProcAddress fnGetProcAddress;
  BYTE *pBase;
};

// Disable compiler optimizations for the shellcode so GCC doesn't 
// move constants or strings to .rdata out of our injected function block.
#pragma GCC push_options
#pragma GCC optimize ("O0")

// Shellcode executed in the target process
DWORD __stdcall LibraryLoader(ManualMappingData *pData) {
  if (!pData || !pData->pBase) return 0;

  BYTE *pBase = pData->pBase;
  IMAGE_DOS_HEADER *pDos = (IMAGE_DOS_HEADER *)pBase;
  IMAGE_NT_HEADERS *pNt = (IMAGE_NT_HEADERS *)(pBase + pDos->e_lfanew);

  // 1. Resolve Imports
  IMAGE_DATA_DIRECTORY *pImportDir = &pNt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT];
  if (pImportDir->Size) {
    IMAGE_IMPORT_DESCRIPTOR *pImportDesc = (IMAGE_IMPORT_DESCRIPTOR *)(pBase + pImportDir->VirtualAddress);
    while (pImportDesc->Name) {
      char *szMod = (char *)(pBase + pImportDesc->Name);
      HMODULE hMod = pData->fnLoadLibraryA(szMod);

      IMAGE_THUNK_DATA *pNameRef = pImportDesc->OriginalFirstThunk ? 
                                   (IMAGE_THUNK_DATA *)(pBase + pImportDesc->OriginalFirstThunk) : 
                                   (IMAGE_THUNK_DATA *)(pBase + pImportDesc->FirstThunk);
      IMAGE_THUNK_DATA *pFuncRef = (IMAGE_THUNK_DATA *)(pBase + pImportDesc->FirstThunk);

      while (pNameRef->u1.AddressOfData) {
        if (IMAGE_SNAP_BY_ORDINAL(pNameRef->u1.Ordinal)) {
          pFuncRef->u1.Function = (DWORD)pData->fnGetProcAddress(hMod, (char *)(pNameRef->u1.Ordinal & 0xFFFF));
        } else {
          IMAGE_IMPORT_BY_NAME *pImport = (IMAGE_IMPORT_BY_NAME *)(pBase + pNameRef->u1.AddressOfData);
          pFuncRef->u1.Function = (DWORD)pData->fnGetProcAddress(hMod, (char *)pImport->Name);
        }
        pNameRef++;
        pFuncRef++;
      }
      pImportDesc++;
    }
  }

  // 2. Process Relocations
  IMAGE_DATA_DIRECTORY *pRelocDir = &pNt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_BASERELOC];
  if (pRelocDir->Size) {
    DWORD delta = (DWORD)pBase - pNt->OptionalHeader.ImageBase;
    if (delta != 0) {
      IMAGE_BASE_RELOCATION *pReloc = (IMAGE_BASE_RELOCATION *)(pBase + pRelocDir->VirtualAddress);
      while (pReloc->VirtualAddress) {
        DWORD count = (pReloc->SizeOfBlock - sizeof(IMAGE_BASE_RELOCATION)) / sizeof(WORD);
        WORD *pList = (WORD *)(pReloc + 1);
        for (DWORD i = 0; i < count; i++) {
          if (pList[i]) {
            DWORD *pPatch = (DWORD *)(pBase + pReloc->VirtualAddress + (pList[i] & 0xFFF));
            *pPatch += delta;
          }
        }
        pReloc = (IMAGE_BASE_RELOCATION *)((BYTE *)pReloc + pReloc->SizeOfBlock);
      }
    }
  }

  // 3. Execute TLS Callbacks (CRITICAL FOR MINGW/C++ DLLs)
  IMAGE_DATA_DIRECTORY *pTlsDir = &pNt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_TLS];
  if (pTlsDir->Size) {
    IMAGE_TLS_DIRECTORY *pTls = (IMAGE_TLS_DIRECTORY *)(pBase + pTlsDir->VirtualAddress);
    if (pTls->AddressOfCallBacks) {
      PIMAGE_TLS_CALLBACK *pCallback = (PIMAGE_TLS_CALLBACK *)pTls->AddressOfCallBacks;
      while (*pCallback) {
        (*pCallback)((LPVOID)pBase, DLL_PROCESS_ATTACH, NULL);
        pCallback++;
      }
    }
  }

  // 4. Call DllMain
  if (pNt->OptionalHeader.AddressOfEntryPoint) {
    pDllMain EntryPoint = (pDllMain)(pBase + pNt->OptionalHeader.AddressOfEntryPoint);
    return EntryPoint((HINSTANCE)pBase, DLL_PROCESS_ATTACH, NULL);
  }
  return 1;
}

DWORD __stdcall LibraryLoaderEnd() { return 0; }
#pragma GCC pop_options

bool InjectManualMap(DWORD pid, const unsigned char *pRawData) {
  IMAGE_DOS_HEADER *pDos = (IMAGE_DOS_HEADER *)pRawData;
  if (pDos->e_magic != IMAGE_DOS_SIGNATURE) {
    Log("[!] Invalid DOS signature\n");
    return false;
  }

  IMAGE_NT_HEADERS *pNt = (IMAGE_NT_HEADERS *)(pRawData + pDos->e_lfanew);
  if (pNt->Signature != IMAGE_NT_SIGNATURE) {
    Log("[!] Invalid NT signature\n");
    return false;
  }

  HANDLE hProc = OpenProcess(PROCESS_ALL_ACCESS, FALSE, pid);
  if (!hProc) {
    Log("[!] Failed to open process (Error: %d)\n", GetLastError());
    return false;
  }

  Log("[*] Allocating memory in target process...\n");
  BYTE *pTargetBase = (BYTE *)VirtualAllocEx(hProc, NULL, pNt->OptionalHeader.SizeOfImage,
                                             MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);

  if (!pTargetBase) {
    Log("[!] Failed to allocate image memory\n");
    CloseHandle(hProc);
    return false;
  }

  Log("[*] Copying headers...\n");
  WriteProcessMemory(hProc, pTargetBase, pRawData, pNt->OptionalHeader.SizeOfHeaders, NULL);

  Log("[*] Copying sections...\n");
  IMAGE_SECTION_HEADER *pSection = IMAGE_FIRST_SECTION(pNt);
  for (int i = 0; i < pNt->FileHeader.NumberOfSections; i++) {
    if (pSection[i].SizeOfRawData) {
      WriteProcessMemory(hProc, pTargetBase + pSection[i].VirtualAddress,
                         pRawData + pSection[i].PointerToRawData, pSection[i].SizeOfRawData, NULL);
    }
  }

  Log("[*] Injecting loader shellcode...\n");
  ManualMappingData data = {0};
  HMODULE hK32 = GetModuleHandleA("kernel32.dll");
  if (!hK32) {
    Log("[!] Could not get kernel32.dll handle\n");
    VirtualFreeEx(hProc, pTargetBase, 0, MEM_RELEASE);
    CloseHandle(hProc);
    return false;
  }

  data.fnLoadLibraryA = (pLoadLibraryA)GetProcAddress(hK32, "LoadLibraryA");
  data.fnGetProcAddress = (pGetProcAddress)GetProcAddress(hK32, "GetProcAddress");
  data.pBase = pTargetBase;

  BYTE *pTargetData = (BYTE *)VirtualAllocEx(hProc, NULL, sizeof(ManualMappingData),
                                             MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
  WriteProcessMemory(hProc, pTargetData, &data, sizeof(data), NULL);

  DWORD shellcodeSize = (DWORD)LibraryLoaderEnd - (DWORD)LibraryLoader;
  BYTE *pTargetShellcode = (BYTE *)VirtualAllocEx(hProc, NULL, shellcodeSize,
                                                  MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);
  WriteProcessMemory(hProc, pTargetShellcode, (void *)LibraryLoader, shellcodeSize, NULL);

  Log("[*] Executing shellcode...\n");
  HANDLE hThread = CreateRemoteThread(hProc, NULL, 0, (LPTHREAD_START_ROUTINE)pTargetShellcode,
                                      pTargetData, 0, NULL);

  if (!hThread) {
    Log("[!] Failed to create remote thread\n");
    VirtualFreeEx(hProc, pTargetBase, 0, MEM_RELEASE);
    VirtualFreeEx(hProc, pTargetData, 0, MEM_RELEASE);
    VirtualFreeEx(hProc, pTargetShellcode, 0, MEM_RELEASE);
    CloseHandle(hProc);
    return false;
  }

  Log("[+] Remote thread spawned! Waiting for loader...\n");
  WaitForSingleObject(hThread, INFINITE);

  DWORD exitCode = 0;
  GetExitCodeThread(hThread, &exitCode);
  Log("[+] Loader returned: %d\n", exitCode);

  CloseHandle(hThread);
  VirtualFreeEx(hProc, pTargetData, 0, MEM_RELEASE);
  VirtualFreeEx(hProc, pTargetShellcode, 0, MEM_RELEASE);
  CloseHandle(hProc);

  if (exitCode == 0) {
    Log("[!] Manual map loader failed internally!\n");
    return false;
  }

  return true;
}

// ============================================
// MAIN LOOP
// ============================================

int main() {
  Log("==========================================\n");
  Log("              SkipFrames\n");
  Log("         (Memory Mapped Edition)\n");
  Log("==========================================\n");

  Log("[*] Waiting for hl.exe...\n");

  DWORD pid = 0;
  while (true) {
    pid = GetProcessIdByName("hl.exe");
    if (pid != 0)
      break;
    Sleep(1000);
  }

  Log("[+] Found hl.exe (PID: %d)\n", pid);

  if (InjectManualMap(pid, g_DllData)) {
    Log("\n[SUCCESS] Memory Mapped Injected!\n");
    Log("--- Commands ---\n");
    Log("  sf_help <0/1>       - Show Help Menu in-game\n");
    Log("--------------------\n");
  } else {
    Log("\n[!] Injection Failed.\n");
  }

  Log("\nYou can close this window now.\n");
  system("pause");
  return 0;
}
